### ISSUE TITLE
Bad Parsing of Array of Tables

### ISSUE THREAD

**Issue by gerrymanoim** [eddelbuettel/rcpptoml#16]
Here's my toml file, taken straight from the spec page:

```toml
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"
```

Using the following code:

```r
library(RcppTOML)
cfg <- parseTOML("toml_test.toml")
str(cfg)
```
I get the following output:
```
Other: variety
Other: variety
List of 1
 $ fruit:Dotted pair list of 2
  ..$ :List of 3
  .. ..$ name    : chr "apple"
  .. ..$ physical:List of 2
  .. .. ..$ color: chr "red"
  .. .. ..$ shape: chr "round"
  .. ..$         : chr "variety"
  ..$ :List of 2
  .. ..$ name: chr "banana"
  .. ..$     : chr "variety"
 - attr(*, "class")= chr [1:2] "toml" "list"
 - attr(*, "file")= chr "toml_test.toml"
```
It seems to me that in both situations "variety" doesn't actually seem to be parsed as a list, but instead parsed an an empty character? 

```
cfg$fruit
[[1]]
[[1]]$name
[1] "apple"

[[1]]$physical
[[1]]$physical$color
[1] "red"

[[1]]$physical$shape
[1] "round"


[[1]][[3]]
[1] "variety"


[[2]]
[[2]]$name
[1] "banana"

[[2]][[2]]
[1] "variety"
```

Session Info:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RcppTOML_0.1.2

loaded via a namespace (and not attached):
 [1] R6_2.2.0        magrittr_1.5    IRdisplay_0.4.4 pbdZMQ_0.2-4   
 [5] tools_3.3.2     Rcpp_0.12.10    crayon_1.3.2    uuid_0.1-2     
 [9] stringi_1.1.5   IRkernel_0.7.1  jsonlite_1.4    stringr_1.2.0  
[13] digest_0.6.12   repr_0.12.0     evaluate_0.10  
```

**Comment by eddelbuettel** [comment]
Confirming -- I see the same result.  Also try setting `verbose=TRUE` to see this:

```
<default print method>
[[fruit]]
        name = "apple"
        [fruit.physical]
                color = "red"
                shape = "round"
        [[fruit.variety]]
                name = "red delicious"
        [[fruit.variety]]
                name = "granny smith"
[[fruit]]
        name = "banana"
        [[fruit.variety]]
                name = "plantain"
</default print method>
```

**Comment by eddelbuettel** [comment]
But look closely at the spec page.  I suspect there is a typo -- `[[fruit.physical]]` seems more logical for the TOML file.  If we do that we get

```r
R> parseToml("/tmp/issue16.toml")
Other: physical
Other: variety
Other: variety
List of 1
 $ fruit:Dotted pair list of 2
  ..$ :List of 3
  .. ..$ name: chr "apple"
  .. ..$     : chr "physical"
  .. ..$     : chr "variety"
  ..$ :List of 2
  .. ..$ name: chr "banana"
  .. ..$     : chr "variety"
R> 
```

**Comment by gerrymanoim** [comment]
The problem seems to be having an array of tables inside of another table. 

The following works fine:

```toml
[[fruit]]
  name = "apple"

[[fruit]]
  name = "banana"
```

This breaks:

```toml
[[fruit]]
  name = "apple"
  [[fruit.variety]]
    name = "red delicious"

```

As does this:

```toml
[fruit]
  name = "apple"
  [[fruit.variety]]
    name = "red delicious"
```

The produced JSON on the spec page makes my thing `[fruit.physical]` was not a typo, i.e. it shows the output as an object

```json
"physical": {
        "color": "red",
        "shape": "round"
      },
```
rather than an array of objects.
